### ISSUE TITLE
Error import name 'path' from 'importlib_resources'

### ISSUE THREAD

**Issue by josiah-liew** [biodiversitydata-se/coidb#21]
Hello, I'm running into some trouble with 'importlib_resources'. The following error: 

```
Traceback (most recent call last):                                                                   
  File "/home/miniconda3/envs/coidb/bin/coidb", line 7, in <module>                              
    from coidb.__main__ import main                                                                  
  File "/home/miniconda3/envs/coidb/lib/python3.9/site-packages/coidb/__main__.py", line 4, in <module>                                                                                               
    from importlib_resources import path as resource_path                                            
ImportError: cannot import name 'path' from 'importlib_resources' (/home/gs2/miniconda3/envs/coidb/lib/python3.9/site-packages/importlib_resources/__init__.py)
```

Running on python 3.9 with conda installation. Any help would be great - thank you! 

Best,
Josiah

**Comment by johnne** [comment]
Hi @josiah-liew ,
Sorry for the late reply. Could you post the output from `conda env export` here? Most likely this problem could be fixed by running `conda upgrade python importlib_resources -n coidb`, but it would be interestingt to see the conda package versions where this occurs.
